### PR TITLE
Changed how the template scaffolding works

### PR DESCRIPTION
**Pull request by alienresident**
## Changed how the template scaffolding works.
- The `manifest.rb` no longer tries to compile or use the standard `config.rb`
- The `manifest.rb` uses a custom `config.rb` that points to the correct font and css folder.
- When you run `compass compile` the custom `config.rb` creates the font and css folder.
- Added  `specimen.scss` which points to  `_type_specimen_1.scss`
- Renamed `_specimen.scss`  to `_type_specimen_1.scss` which can be duplicated
- Added a `README.mkdn`to the fonts folder (otherwise the folder won't be created)
- Updated the @font-face mixin to add `$font-file-name` to the mixin
- Added CSS to wfs to add $font-name via a pseudo class to the H1 and TH instead of replacing {FONT NAME} 
- Wrapped {FONT NAME} is a span tag to hide it.
- Updated the version number

### CODE REVIEW

**Comment by mirisuzanne** [comment]
Thanks! This looks great!

**Comment by mirisuzanne** [comment]
I've given you core access to this, if you're interested in helping maintain it over time.

**Comment by alienresident** [comment]
Yes, I am happy to help you maintain it! 

Thanks for pulling my code and giving me commit access.

**Comment by mirisuzanne** [comment]
No problem, thanks for jumping in. :)

**Pull request merged**
